SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_himot_dancetrack.yaml

# Inference settings:
INFERENCE_MODEL: ./outputs/r50_deformable_detr_himot_dancetrack/checkpoint_0.pth
INFERENCE_DATASET: DanceTrack
INFERENCE_SPLIT: val
INFERENCE_MODE: evaluate    # evaluate or submit
INFERENCE_GROUP: default
INFERENCE_MAX_LONGER: 1440
INFERENCE_DTYPE: FP32
ASSIGNMENT_PROTOCOL: object-max
MISS_TOLERANCE: 30
DET_THRESH: 0.3
NEWBORN_THRESH: 0.6
ID_THRESH: 0.3
IOU_THRESH: 0.1
EMB_COS_WEIGHT: 1.0
EMB_MSE_WEIGHT: 0.25
IOU_COST_WEIGHT: 1.0
AREA_THRESH: 0
INFERENCE_ONLY_DETR: False

# Outputs settings:
OUTPUTS_DIR: ./outputs/r50_deformable_detr_himot_dancetrack
